### ISSUE TITLE
ArgumentError - wrong number of arguments (given 1, expected 2)

### ISSUE THREAD

**Issue by complex-user** [c477y/adulttime_dl#2]
Hello, I am trying to resolve this issue where I'm only getting this error:

```
/app/adulttime_dl # ./exe/./adulttime_dl download --cookie-file=cookies/cookies.txt --config=config/config.yaml adulttime
[23:36:16] [INFO ] youtube-dl installed with version 2023.11.30
[23:36:16] [INFO ] [DATABASE_INIT] /app/adulttime_dl/adt_download_status.store
[23:36:16] [INFO ] [PROCESS START]
[23:36:16] [INFO ] [PROCESSING URL] https://members.adulttime.com/en/pornstar/view/Leana-Lovings/91441
[23:36:16] [FATAL] ArgumentError - wrong number of arguments (given 1, expected 2)
/app/adulttime_dl # 
```

My config file:
```
# [List] Skip studios based on name
# If any scene belongs to that studio, the scene will be skipped
skip_studios: []
# [List] Skip performers based on name
skip_performers: []
# [Boolean] Skip downloading scenes with only female actors
# This only works with certain sites that provide gender information for performers
skip_lesbian: false
# [String] Path to a cookie file. Used only for sites that require membership
# information. Use a browser extension to get a cookie file
# If you are on mozilla, you can use https://addons.mozilla.org/en-GB/firefox/addon/cookies-txt/
cookie_file: cookies.txt
# [String] Name of file that tracks list of downloaded scenes
store: adt_download_status.store
# [String] Name of downloader tool to use. Currently supports youtube-dl
# and yt-dlp
# Ensure that the downloader is available in your $PATH
downloader: youtube-dl
# [String] Directory to download scenes. '.' means current directory
download_dir: "."
# [String] Resolution of scene to download. Accepts one of 'sd', 'hd', and 'fhd'
quality: hd
# [Number] Number of parallel download jobs
parallel: 1
# [Boolean] Enable/Disable verbose logging
verbose: true
# [Boolean] Just log to console, doesn't download anything
dry_run: false
# [String] Arguments to pass to external downloader
# Check the documentation of youtube-dl or yt-dlp for details
# eg. --external-downloader aria2c --external-downloader-args
# "-j 8 -s 8 -x 8 -k 5M"
downloader_flags: ''
urls:
  # [List] URLs of performer names that will be downloaded
  performers: [https://members.adulttime.com/en/pornstar/view/Leana-Lovings/91441]
  # [List] URLs of movie names that will be downloaded
  movies: [https://members.adulttime.com/en/video/howwomenorgasm/Leana-Loves-To-Be-Stimulated/233394]
  # [List] URLs of scene names that will be downloaded
  scenes: []
# [OPTIONAL] These are site specific configuration only needed for some sites
site_config:
  blowpass:
    # Get Algolia credentials from Web Console
    algolia_application_id:
    algolia_api_key:
```

I'm not sure where I would supply additional arguments?
